name: review

on:
 workflow_dispatch:
 
jobs:
  Review:
  - uses: Automattic/action-required-review@v3
     with:
      token: ${{ secrets.REQUIRED_REVIEWS_TOKEN }}
      requirements: |
            - paths: unmatched
              teams:
                - rajethauday98@gmail.com
