name: review

on:
 workflow_dispatch:
 
jobs:
  Review:
   runs-on: ubuntu-latest
   steps:
   - uses: Automattic/action-required-review@v3
     with:
       token: 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
       requirements: |
            - paths: unmatched
              teams:
                - rajethauday98@gmail.com
